### ISSUE TITLE
How to specify exclude keys in playbook?

### ISSUE THREAD

**Issue by igoqueen5** [CiscoDevNet/ansible-pyats#2]
Hi. I have two questions to use genie.py.

1, Could I use genie_parser and genie_diff with log files?
for example:
```
- name: Read in snaphot file
  set_fact:
    snapshot_data1: "{{ lookup('file', before_snapshot, errors='ignore') }}"
    snapshot_data2: "{{ lookup('file', after_snapshot, errors='ignore') }}"

- name: before parsing output
  set_fact:
    before_parsed_output: "{{ before_snapshot | pyats_parser(command, 'nxos') }}"

- name: after parsing output
  set_fact:
    after_parsed_output: "{{ after_snapshot | pyats_parser(command, 'nxos') }}"

- name: Diff current and snapshot
  set_fact:
    diff_output: "{{ before_parsed_output | pyats_diff(after_parsed_output, exclude=exclude_list) }}"

- name: debug
  copy:
    content: "{{ diff_output }}"
    dest: "./log/genie_diff.txt"

```

This playbook is using 'show ip route vrf all'.  
Once I run this playbook, I got an error message which is "AttributeError: 'dict' object has no attribute 'split'".

Is it because of using log files? Do I need to execute command and parsing by using 'stdout'?

2, How can I exclude unnecessary keys from the diff result?
Now I'm using genie.py as following below.
I commented out a part of genie.py and using it because of an error an error occured as I mentioned.

```
#config1 = Config(output1)
        #config1.tree()
        #dict1 = config1.config
#
        #config2 = Config(output2)
        #config2.tree()
        #dict2 = config2.config

        dd = Diff(output1, output2, mode=mode, exclude=exclude)
        dd.findDiff()
        #diff = str(dd)
        #diff_list = diff.split('\n')
        return dd
```

And I create a exclude list.
```
exclude_list:
  - updated
```
But it could not work.

I also tried "- vrf", "- routes" and  "- next_hop", but "- next_hop" were not work well.

What I want to actual exclude key is 'updated'. 
How can I do that?

Thanks!
