### ISSUE TITLE
Support Multiple Commands

### ISSUE THREAD

**Issue by supertylerc** [CiscoDevNet/ansible-pyats#7]
It would be great if this role and its tasks supported multiple commands at once.  An example playbook:

```yaml
---

- name: Check for any differences after two minutes
  hosts: all
  vars:
    commands:
      - show version
      - show ip bgp summary
      - show ip route
  roles:
    - ansible-pyats
  tasks:
    - include_role:
        name: ansible-pyats
        tasks_from: snapshot_command
      vars:
        command: "{{ commands }}"
        file: "{{ inventory_hostname }}.json"
    - pause:
        minutes: 2
    - include_role:
        name: ansible-pyats
        tasks_from: compare_command
      vars:
        command: "{{ commands }}"
        file: "{{ inventory_hostname }.json"
```

Something similar to this is possible with NAPALM, which accepts a list of commands, or with `ios_commands`, which also accepts a list of commands.  However, I don't think it's currently possible with the modules in this repo.  It would be great if these modules supported multiple commands.  The old `with_items` and `loop` patterns appear to be severely discouraged (see the `apt` module, for example), so it would be best to not have to resort to those options.
